name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run audit
        #        Change back to high once there is solution for semantic-release => dot-prop Prototype Pollution
        run: npm audit --audit-level=critical
      - name: install dependencies and build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: lint
        run: npm run lint
      - name: unit tests
        run: npm run test:cov
        env:
          CI: true
      - name: e2e tests
        run: npm run test:e2e
